version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/ChenBonBon/problem-resolver/backend"