// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameProblemAnswer = "problem_answers"

// ProblemAnswer mapped from table <problem_answers>
type ProblemAnswer struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProblemID int32     `gorm:"column:problem_id;not null" json:"problem_id"`
	Answer    string    `gorm:"column:answer;not null" json:"answer"`
	Status    string    `gorm:"column:status;not null;default:'enabled'::character varying" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	CreatedBy int32     `gorm:"column:created_by;not null" json:"created_by"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	UpdatedBy int32     `gorm:"column:updated_by" json:"updated_by"`
}

// TableName ProblemAnswer's table name
func (*ProblemAnswer) TableName() string {
	return TableNameProblemAnswer
}
