// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/lib/pq"
)

const TableNameProblem = "problems"

// Problem mapped from table <problems>
type Problem struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	CreatedBy   int32     `gorm:"column:created_by;not null" json:"created_by"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	UpdatedBy   int32     `gorm:"column:updated_by" json:"updated_by"`
	Difficulty  string    `gorm:"column:difficulty;not null" json:"difficulty"`
	Status      string    `gorm:"column:status;default:'Enabled'" json:"status"`
	Types       pq.Int32Array    `gorm:"column:types;type:integer[];default:'{5}'::integer[]" json:"types"`
}

// TableName Problem's table name
func (*Problem) TableName() string {
	return TableNameProblem
}
