// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserCode = "user_codes"

// UserCode mapped from table <user_codes>
type UserCode struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Code      string    `gorm:"column:code;not null" json:"code"`
	Used      bool      `gorm:"column:used;not null" json:"used"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	ExpiredAt time.Time `gorm:"column:expired_at;not null;default:(now() + '1 day'::interval)" json:"expired_at"`
	UsedAt    time.Time `gorm:"column:used_at" json:"used_at"`
}

// TableName UserCode's table name
func (*UserCode) TableName() string {
	return TableNameUserCode
}
