CREATE TABLE IF NOT EXISTS user_codes(
   id SERIAL PRIMARY KEY,
   email VARCHAR (64) NOT NULL,
   code VARCHAR (6) NOT NULL,
   used BOOLEAN NOT NULL DEFAULT FALSE,
   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
   expired_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '1 day'
   used_at TIMESTAMPTZ
);